const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `All purpose flour, sugar,buttermilk, eggs, butter, maple syrup `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `100% Beef, Burger Bun, Salad, Tomato, Pickles, Homemade Burger sauce, Cheddar, Blue Cheese  `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Milk, Strawberry, sugar, Donut, Cream, selected toppings`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Classic bread omlet, beans with homemade sauce, cheese, Coffee `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `100% vegan Soja, Burger Bun, Salad, Tomato, Pickles, Homemade Burger sauce, Cheddar`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Milk, Oreo biscuit  , sugar, Cream,  selected toppings`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Becon, Egg, Cheddar, Cheese, Lattice, salt, pepper `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `100% Beef, Burger Bun, Salad, Tomato, Pickles, Homemade Burger sauce, Cheddar, Blue Cheese, with French fries  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Milk, Strawberry, sugar, Donut, Cream, selected toppings`,
  },
];
export default menu;
